### ISSUE TITLE
TailscaleGX 1.1 conflict with ShutdownMonitor 3.1

### ISSUE THREAD

**Issue by wetty** [kwindrem/TailscaleGX#1]
I have ShutdownMonitor v3.1 installed and would like to install TailscaleGX, but it gives me a conflict warning.

"ShutdownMonitor must not be installed"

**Comment by kwindrem** [comment]
With SetupHelper v7.x this is indeed the case. Both packages modify the same file. SetupHelper v8.x will address this issue and allow two packages to modify the same file assuming no overlaps occur in the modifications.

SetupHelper v8.x is a major change and is undergoing an extended beta test period.  I recommend installing beta code only if you have command line access (ssh) to insure you have a recovery path should any bug render the GUI (and PakcageManager with it) inaccessible. I have tested SetupHelper v8.x on Tailscale and ShutdownMonitor so the risk of issues in your case is small.

If you want to try v8.x, set SetupHelper's branch/tag to beta. This will allow both packages to install. If you experience any issues, please post an issue to the SetupHelper issues section on GitHub..
