### ISSUE TITLE
Not installing under Venus OS 3.40

### ISSUE THREAD

**Issue by peregrines2** [kwindrem/TailscaleGX#2]
Trying to install TailscaleGX on Venus OS 3.4 (20240716...) (Rpi 4 8GB).
Unfortunately it is not installing (had to manually add it).
"TailscaleGX install unkown error 1"

Or maybe I am just doing something wrong?

<img width="523" alt="Bildschirmfoto 2024-07-19 um 06 02 42" src="https://github.com/user-attachments/assets/1aa58a3a-7e75-4ecf-aff2-c3ee8e96327c">

**Comment by kwindrem** [comment]
I have no idea what error 1 is nor do I see a way for the code to generate it.

You say "manually add it". Is that from the command line or ???

What version of SetupHelper is running?

Please zip the PackageManager log file and post here.
The log file is: /data/log/PackageManager/current

**Comment by peregrines2** [comment]
Thank You form your support!
"manually add it" TailscaleGX was not present in the list after installing Package Manager.
So I added it  (as described here)  
.................................
"If not in the list, select new and fill in the details:

Packagename: TailscaleGX

GitHub user: kwindrem

GitHub branch or tag: latest

then tap Proceed"


[current.zip](https://github.com/user-attachments/files/16329379/current.zip)

**Comment by kwindrem** [comment]
The default list is only used the first time PackageManager runs. After that, the previous list remains.
In order to refresh the list you can perform the reinitialize package manager in the restart menu

**Comment by peregrines2** [comment]
THANK YOU!
This worked perfectly fine :) 
Please keep up your fantastic work!
